# Generated by Django 5.0.3 on 2024-04-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Memory', '0002_faqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQ'},
        ),
    ]
